import Script from "next/script";
import "../../node_modules/bootstrap/dist/css/bootstrap.rtl.min.css"
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ScrollTopBtn from "@/components/modules/ScrollTopBtn/ScrollTopBtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/css/style.css" />
        <link rel="stylesheet" href="/assets/css/skin_color.css" />
      </head>
      <body suppressHydrationWarning>
          {children}
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
        <ScrollTopBtn />
      </body>
    </html>
  );
}
